permalink:           "/:title"

title:               NikiYani
url:                 https://www.nikiyani.github.io
canonical_url:       'http://www.nikiyani.github.io'
description:         "Personal blog of Nikita Yanchenkov about 3D modeling and computer graphics"
paginate:            7
baseurl:             ""
logo:                '/public/logo.png'

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate #Деление главной на страницы
# - jekyll-gist #Интеграция GitHub Gists
  - jekyll-sitemap #Автоматическое построение карты сайта
# - jekyll-seo-tag #SEO-оптимизация

pages_list:    
  Sitemap: '/sitemap'   
  About me: '/about_me'
  Tooling: '/tooling'

tag_page: '/sitemap'
excerpt_separator: "<!--more-->"

# About
author:
  email:             nekitgoldrush@yandex.ru
  vk:                https://vk.com/hotline_dolgopa
  sketchfab:         https://sketchfab.com/NikiYani/models
  twitter:           https://twitter.com/NikiYaniCG
  facebook:          https://www.facebook.com/NikiYani3D
  instagram:         https://www.instagram.com/zack_drug/
  youtube:           https://www.youtube.com/channel/UC0vCTRWN-R9NRVrYb-0ZZVQ?view_as=subscriber
  telegram:          https://t.me/Hotline_Dolgopa

# Social
social:
  name: NikiYani
  links:
        https://vk.com/hotline_dolgopa
        https://sketchfab.com/NikiYani
        https://twitter.com/NikiYaniCG
        https://www.facebook.com/NikiYani3D
        https://www.instagram.com/zack_drug/
        https://www.youtube.com/channel/UC0vCTRWN-R9NRVrYb-0ZZVQ?view_as=subscriber
        https://t.me/Hotline_Dolgopa
        
# Language
lang: ru_RU